### ISSUE TITLE
CI 错误信息修正

### ISSUE THREAD

**Issue by kinosang** [top-think/think#82]
[top-think/think Job #35.2 Log](https://gist.github.com/kinosang/0457be03917b9376b030)

##TODO:

###PHP LINT
无

###PHP_CodeSniffer
* [x] <del>PHPCBF自动修复 bc1b5f7c516375e78b6212dacff72293bf84ab19</del>
* [ ] <del>PHPCBF结果审计</del>
* [ ] <del>其他问题手动修复 #83</del>

降级 PHPCS 检查

###PHP Copy/Paste Detector
* [ ] <del>think/thinkphp/library/org/image/driver/gd.php:137-221
    think/thinkphp/library/org/image/driver/imagick.php:115-199</del>

* [ ] <del>think/thinkphp/library/org/image/driver/gd.php:275-330
    think/thinkphp/library/org/image/driver/imagick.php:270-325</del>

* [ ] <del>think/thinkphp/library/org/image/driver/gd.php:401-461
    think/thinkphp/library/org/image/driver/imagick.php:423-483</del>

* [ ] <del>think/thinkphp/library/org/image/driver/gd.php:523-595
    think/thinkphp/library/org/image/driver/imagick.php:566-638</del>

* [ ] <del>think/thinkphp/library/org/upload/driver/qiniu/qiniu_storage.php:270-299
    think/thinkphp/library/org/upload/driver/upyun.php:119-148</del>

* [ ] <del>think/thinkphp/library/think/db/driver.php:167-190
    think/thinkphp/library/think/db/driver.php:226-249</del>

* [ ] <del>think/thinkphp/library/think/db/driver.php:134-386
    think/thinkphp/library/think/db/lite.php:120-372</del>

* [ ] <del>think/thinkphp/library/think/db/driver.php:1177-1263
    think/thinkphp/library/think/db/lite.php:455-541</del>

* [ ] <del>think/thinkphp/library/think/model.php:705-735
    think/thinkphp/library/traits/model/auto.php:28-58</del>

降级 PHPCPD 检查

###phpmd
<del>数量太多，不在此列出</del>

取消 PHPMD 检查

###phpunit
* [X] 创建 bootstrap 文件
* [x] 创建基础功能测试
